# .streamlit/secrets.toml

[auth]
redirect_uri = "your redirect_uri"
cookie_secret = "a-long-string"

client_id = ""
client_secret = ""
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"